version: "3.8"
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app-network

  management:
    build: ./management-service
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
    volumes:
      - ./certs:/certs
    networks:
      - app-network
    depends_on:
      - rabbitmq

  retriever:
    build: ./retriever-service
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=development
    volumes:
      - ./certs:/certs
    networks:
      - app-network
    depends_on:
      - rabbitmq

  gateway:
    build: ./API-gateway
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - MANAGEMENT_URL=https://management:3001
      - RETRIEVER_URL=https://retriever:3002
    volumes:
      - ./certs:/certs
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
