apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: leonelholguin/popularpruebatecnica:gateway
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: certs
              mountPath: /certs
          env:
            - name: NODE_ENV
              value: "development"
            - name: MANAGEMENT_URL
              value: "https://management-service:3001"
            - name: RETRIEVER_URL
              value: "https://retriever-service:3002"
      volumes:
        - name: certs
          secret:
            secretName: ssl-certs
