apiVersion: v1
kind: Service
metadata:
  name: management-service
spec:
  type: NodePort
  selector:
    app: management
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
      nodePort: 30081
---
apiVersion: v1
kind: Service
metadata:
  name: retriever-service
spec:
  type: NodePort
  selector:
    app: retriever
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
      nodePort: 30082
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  selector:
    app: rabbitmq
  ports:
    - name: amqp
      protocol: TCP
      port: 5672
      targetPort: 5672
    - name: management
      protocol: TCP
      port: 15672
      targetPort: 15672
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  type: NodePort
  selector:
    app: gateway
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
